title: "Moj ZET App Guide"
description: "a practical guide for advanced use of the Moj ZET App"

# Remote theme setup
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Just the Docs configuration
just_the_docs:
  # Collapses child pages under their parent in the sidebar
  collapse_section_nav: true

nav:
  - "Home": "README.md"
  - "Croatian Guide": "README_HR.md"
nav_enabled: true

color_scheme: dark