title: "Moj ZET App Guide"
description: "a practical guide for advanced use of the Moj ZET App"

# Remote theme setup
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Just the Docs configuration
just_the_docs:
  # Collapses child pages under their parent in the sidebar
  collapse_section_nav: true

nav:
  - "Home": "README.md"
  - "Croatian Guide": "README_HR.md"
nav_enabled: true

nav_external_links:
 - title: The App Guide on GitHub
   url: https://github.com/fscek/moj-zet-app-guide/
   hide_icon: false # set to true to hide the external link icon - defaults to false
   opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

color_scheme: dark